version: '3.5'

services:
  mrsm-compose:
    build:
      context: "./"
      dockerfile: "./docker/Dockerfile"

    ### Override the `bootstrap.sh` entrypoint for interactive development and testing.
    entrypoint: ["/app/docker/sleep_forever.sh"]

    environment:

      ### NOTE: Do not store secrets in your compose file;
      ###       you may reference individual keys
      ###       or the entire JSON from an environment variable.
      MRSM_EXAMPLE_SECRET: |-
        {
          "username": "foo",
          "password": "bar"
        }

      ### Feel free to override `sql:main` or add your own connectors.
      ### Just make sure you also add them to `mrsm-compose.yaml` using the `MRSM{}` syntax.
      # MRSM_SQL_MAIN: $MRSM_SQL_MAIN

    network_mode: "host"
    volumes:
      - "./:/app"
    init: true
    tty: true
