version: '3.5'

services:

  mrsm-compose:
    build:
      context: "./"
      dockerfile: "./docker/Dockerfile"

    ### Override the `bootstrap.sh` entrypoint for interactive development and testing.
    entrypoint: ["/app/docker/sleep_forever.sh"]

    environment:
      MRSM_SQL_ETL: "$MRSM_SQL_ETL"
      MRSM_MONGODB_LOCAL: "$MRSM_MONGODB_LOCAL"
      MRSM_CONFIG: |-
        {
          "meerschaum": {
            "instance": "sql:etl"
          }
        }

    network_mode: "host"
    volumes:
      - "./:/app:rw,z"
    init: true
    tty: true
    user: "meerschaum:meerschaum"


  mongodb:
    image: "mongo"
    network_mode: "host"
