### Comment these out when running outside of Docker.
root_dir: "/meerschaum"
plugins_dir:
  - "/meerschaum/plugins"
  - "/app/plugins"

project_name: "carolina-codes-weather"

sync:
  min_seconds: 30
  pipes:

    - connector: "plugin:noaa"
      metric: "weather"
      location: "sc"
      parameters:
        noaa:
          stations:
            - "KGMU"
            - "KCEU"
            - "KJZI"

    - connector: "plugin:noaa"
      metric: "weather"
      location: "nc"
      instance: "mongodb:local"
      parameters:
        noaa:
          stations:
            - "KCLT"
            - "KCEU"
            - "KJZI"

    - connector: "plugin:clone"
      metric: "weather"
      target: "weather_combined"
      parameters:
        sources:
          - pipe:
              connector: "plugin:noaa"
              metric: "weather"
              location: "sc"
          - pipe:
              connector: "plugin:noaa"
              metric: "weather"
              location: "nc"

    - connector: "sql:etl"
      metric: "weather"
      location: "fahrenheit"
      target: "weather_fahrenheit"
      columns:
        datetime: "timestamp"
        station: "station"
      parameters:
        fetch:
          backtrack_minutes: 1440
        query: |-
          SELECT
            "timestamp",
            "station",
            "location",
            (("temperature (wmoUnit:degC)" * 1.8) + 32) AS "fahrenheit"
          FROM "weather_combined"

    - connector: "sql:etl"
      metric: "weather"
      location: "avg"
      columns:
        datetime: "day"
        station: "station"
      parameters:
        fetch:
          backtrack_minutes: 1440
        query: |-
          SELECT
            time_bucket('1 day', "timestamp") AS "day",
            "station",
            "location",
            ROUND("fahrenheit"::NUMERIC, 2) AS "avg_temp"
          FROM "weather_fahrenheit"
      
plugins:
  - "noaa"
  - "mongodb-connector"
  - "clone"

config:
  meerschaum:
    instance: "sql:etl"
    connectors:
      sql:
        etl: MRSM{meerschaum:connectors:sql:etl}
      mongodb:
        local: MRSM{meerschaum:connectors:mongodb:local}
        

### Other environment variables to include (e.g. AWS creds).
environment: {}
